name: PowerDict

channels:
  - conda-forge
  
dependencies:
  - python>=3.7
  - pandas
  - matplotlib
  - jupyterlab
  - lxml
  - html5lib
  - beautifulsoup4
  - seaborn
  - mkdocs==1.2.1
  - mkdocs-material
  - twine
  - typer
  - tqdm
  - jinja2
  - pip
  
  - pip:
      - -e .
      - nbdev
      - feautils
      - git+https://github.com/ayrtonb/frictionless-py.git@60789d30fe7729ed898a20d4dd50fe823381e325
      - mkdocs-material-extensions
      - mkdocstrings
      - configparser
      - junix
