site_name: Power-Station-Dictionary
repo_url: https://github.com/OSUKED/Power-Station-Dictionary
repo_name: Power-Station-Dictionary
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - search.suggest
  palette:
    primary: black

extra:
  generator: false
      
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - footnotes
  - attr_list
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
      
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Home: 
    - Welcome: index.md
    - Method: generation-process.md
  - Development:
    - Sources: 01-source-data.md
    - Definitions: 02-data-definitions.md
    - Construction: 03-database-construction.md
    - Updates: 04-updates-and-cleaning.md
    - Pipeline: 05-pipeline.md