site_name: Power-Station-Dictionary
repo_url: https://github.com/OSUKED/Power-Station-Dictionary
edit_uri: edit/main/docs/
repo_name: Power-Station-Dictionary
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - search.suggest
  palette:
    primary: black

extra:
  generator: false
      
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - footnotes
  - attr_list
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
      
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tables.js
  
nav:
  - Home: 
    - Welcome: index.md
  - Sites:
    {% for object_name in object_names %}
    - {{object_name}}: objects/{{object_name}}.md{% endfor %}
